export { default as Home } from "./Home";
export { default as Admin } from "./Admin";
export { default as ProductList } from "./ProductList";
export { default as ProductDetail } from "./ProductDetail";
export { default as Contact } from "./Contact/Contact";
export { default as ContactIn } from "./Contact/ContactIn";
export { default as ContactPk } from "./Contact/ContactPk";
export { default as ContactAll } from "./Contact/ContactAll";
export { default as ErrorPage } from "./ErrorPage";
